name: 生成我的RNDIS内核
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装工具
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm crossbuild-essential-arm64

      - name: 编译内核
        run: |
          mkdir out
          # 合并底座配置和你的 Renoir 配置
          make O=out ARCH=arm64 vendor/lahaina_qgki_defconfig vendor/renoir_QGKI.config
          make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 -j$(nproc)
          
      - name: 只要 Image
        uses: actions/upload-artifact@v4
        with:
          name: Renoir-Kernel
          path: out/arch/arm64/boot/Image
